### ISSUE TITLE
Inconsistent version numbers

### ISSUE THREAD

**Issue by Rhialto** [SDL-Hercules-390/crypto#5]
Here also `README.md` and the `build` script disagree.

**Comment by Fish-Git** [comment]
The version number of the _package_ is defined by statements within the package's [CMake script](https://github.com/SDL-Hercules-390/crypto/blob/master/CMakeLists.txt):

https://github.com/SDL-Hercules-390/crypto/blob/837705eff938ca044f2eab5f1ea5cd83b2b0ece7/CMakeLists.txt#L9-L18

which matches both the packages's documentation (README) and what is reported by Hercules too during startup as well:

<pre>
<b>HHC01417I Built with crypto external package version 1.0.0.49-g837705e</b>
HHC01417I Built with decNumber external package version 3.68.0.99-gda66509
HHC01417I Built with SoftFloat external package version 3.5.0.102-g42f2f99
HHC01417I Built with telnet external package version 1.0.0.59-g2aca101
</pre>

Closing as Invalid (User Error).
